services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    container_name: crypto_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto
    ports:
      - '4001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
