services:
  backend:
    image: ghcr.io/wtswistak/hydro:latest
    container_name: crypto_backend
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      PORT: 4000
      HOST: 0.0.0.0

  postgres:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    container_name: crypto_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '4001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: crypto_redis
    ports:
      - '4002:6379'

  predict-service:
    image: ghcr.io/wtswistak/fee-predictor:latest
    container_name: fee_predict
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      API_KEY: ${FEE_PREDICTION_API_KEY}

volumes:
  postgres_data:
