name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set VERSION env variable
        run: echo "VERSION=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Make image public
        run: |
          gh api --method PATCH /user/packages/container/${{ github.repository }}/versions --field visibility=public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
